### ISSUE TITLE
HTTP method body expects Record<string, string>

### ISSUE THREAD

**Issue by zaida04** [cordis-lib/cordis#23]
## Example Code

```ts
import { RestManager } from "@cordis/rest";
import { buildRestRouter } from "@cordis/routers";

const manager = new RestManager(process.env.DISCORD_TOKEN);
const rest = buildRestRouter(manager);

await rest.channels["500765481788112916"].messages.post({
      data: {
            content: "TESTING MESSAGES",
            tts: false,
            embed: {},
      },
});
```

## Issue
In the data object, the keys `tts` and `embed` are invalid because data is expecting only a `Record<string, string>`, which should be improper considering things like objects can be nested in the body and values like booleans and numbers also exist.

## Potential Solution
change `Record<string, string>` to `Record<string, any>`

**Comment by didinele** [comment]
Yeah, good catch, this happened because I was using that type for queries and I didn't realize I'd need something else for data.

Will fix tonight.
