### ISSUE TITLE
shardCount addition fails when shardCount is set to "auto"

### ISSUE THREAD

**Issue by zaida04** [cordis-lib/cordis#25]
## Code

https://github.com/cordis-lib/cordis/blob/6153918a5c3a14bac0108e23411a362b0e937d6d/libs/gateway/src/websocket/Cluster.ts#L252-L254

## Issue
This line prompts the eslint error of `Operands of '+' operation must either be both strings or both numbers` cause of `this.startingShard + this.shardCount;`
This is because even though there is a check earlier for if shardCount is auto and reassigns it to reccomendedShards, the "auto" value still falls through. This can be fixed with a type assertion guaranteeing this.shardCount is a number. 

## Solution

`this.startingShard + this.shardCount;` => `this.startingShard + (this.shardCount as number)`

*will create PR shortly*

**Comment by didinele** [comment]
Uh, that's a bit odd, we aren't running into this in CI, are you sure it's not a local issue? i.e have you `pnpm `i in the root and also compiled the whole codebase? `pnpm run build` (in the root)

**Comment by zaida04** [comment]
As weird as it is, I did that and the vsc extension seems to be the only thing setting that off. Must be something with my config in that case.
