### ISSUE TITLE
Add docs workflow

### ISSUE THREAD

**Issue by zaida04** [cordis-lib/cordis#28]
## Request

Add a docs workflow to ensure we have up to date docs and have less reliance on manual work 

### When?
On push to master (e.x. merged prs or straight commits) 

### Steps
- will build the libs
- build the typedoc docs
- push to https://github.com/cordis-lib/cordis-lib.github.io

### Additional Notes
We will need to make use of the GITHUB_TOKEN environment variable in order to have permissions to push straight to the master branch of cordis-lib.github.io

**Comment by didinele** [comment]
Fyi master/main is guarded, and can not be pushed to directly.

**Comment by zaida04** [comment]
master/main of this repo or of the docs repo

**Comment by didinele** [comment]
Was quoting
> When?
On push to master (e.x. merged prs or straight commits)

Yeah, this repository.
