### ISSUE TITLE
0.2.0 meta thread🎉

### ISSUE THREAD

**Issue by didinele** [cordis-lib/cordis#54]
Currently decided things about this release:

- It *will* be a breaking release, as described bellow.
- ~~When it's being released is unknown. As usual, we roll out new versions on Sundays unless there's emergency fixes, so it'll be "on the sunday corresponding to the week it's done in"~~ Coming out this week!

Done:
- The introduction of `@cordis/util` with #32
  - `@cordis/snowflake` is getting entirely deprecated, becoming a part of `util` instead
  - `makeDiscordCdnUrl` is being from `@cordis/common` moved into `@cordis/util` [BREAKING]
  - #46 is being resolved
  - #29 is being resolved, with the primary goal of having helper functions for ~~all~~ most documented API endpoints exposed by Discord
- #35 - Small breaking change removing a few redundant methods from `RedisStore` [BREAKING]
- #52 - Gets rid of some left-over implicit caching done by `@cordis/gateway` [BREAKING]
- #59 - Deprecation of `@cordis/routers` in favor of placing its functionality into `@cordis/rest`
- #60 - The ability to resume a gateway connection while initially connecting to the gateway.
- #61 - The ability of injecting dependencies and own functionality into the Cordis gateway service without the need of forking or overwriting the base source file.

**Comment by didinele** [comment]
Besides #61 everything can be merged right now.

**Comment by didinele** [comment]
Everything has just been merged! Releasing tomorrow.

**Comment by zaida04** [comment]
Closed via 7238dc7aabe996450138f164e5c0d6bfd63ee25a
