### ISSUE TITLE
Use a bundler to reduce gateway image size

### ISSUE THREAD

**Issue by didinele** [cordis-lib/cordis#63]
**Is your feature request related to a problem? Please describe.**
With #24 ([0.1.6](https://github.com/cordis-lib/cordis/releases/tag/0.1.6)) the size of the gateway service has been reduced significantly but it still feels fairly large.

**Describe the ideal solution**
I feel like this could be pushed further significantly by using a bundler such as rollup, snowpack or webpack.

**Describe alternatives you've considered**
Leaving it as is, I suppose, but I believe the size optimization is worth it.

**Comment by tbnritzdoge** [comment]
use esbuild for fast build times and sex bundling

**Comment by didinele** [comment]
Decided against this since under 100MBs is already like, fairly damn good for nodejs.
