### ISSUE TITLE
Automatic version roll-out

### ISSUE THREAD

**Issue by didinele** [cordis-lib/cordis#64]
**Is your feature request related to a problem? Please describe.**
Releasing versions manually is pain.

**Describe the ideal solution**
Would be neat to figure out a way to automatically push out a release via Actions. Think all we'd have to do is to monitor the `version` in the root `package.json` and see if it's changed - and, if it did, run `pnpm run release` from the current main branch.

**Describe alternatives you've considered**
Sticking to the current approach, but pain

**Comment by NicholasG04** [comment]
https://github.com/EndBug/version-check

**Comment by didinele** [comment]
Implemented in #77
