### ISSUE TITLE
Changelog generation

### ISSUE THREAD

**Issue by didinele** [cordis-lib/cordis#81]
I think [this](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) config looks acceptable for our commit messages.

From there we can use [this](https://github.com/conventional-changelog/standard-version) to generate our changelog.

Thoughts on my chosen commit-lint config? @zaida04

**Comment by zaida04** [comment]
That config looks good to me. We can make additional use of commit lints angular commit convention plugin if we choose to, which is pretty close to the linked config

**Comment by zaida04** [comment]
Partially completed with #86

**Comment by didinele** [comment]
Actually, fully completed as described in that PR :p

Process remains semi-manual.
